#!/bin/sh
# A stand-in for a rendering program, for the tests and the examples of
# docs/design/rendering.md. It reads what it is handed and answers one small
# PDF, the same whatever it was handed: what it writes is not a rendering of
# anything. It is here so that a record of a PDF can be made where no
# rendering program is installed.
cat >/dev/null
cat <<'EOF_OF_THE_PDF'
%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>
endobj
4 0 obj
<< /Length 189 >>
stream
BT /F1 14 Tf 72 720 Td 18 TL (Refund decision) Tj T* (The refund of 149.50 CAD is approved under the refund policy.) Tj T* (\(A stand-in for a rendering program wrote this file.\)) Tj T* ET
endstream
endobj
5 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>
endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000241 00000 n 
0000000481 00000 n 
trailer
<< /Size 6 /Root 1 0 R >>
startxref
578
%%EOF
EOF_OF_THE_PDF
