//go:build ignore

// gen_policy writes policy_table.go: every code point display policy 1
// refuses (docs/design/tool-descriptors.md), from the Unicode 15.0.0
// character database, so the table is that version's whatever release of
// Go builds the adapter. It reads three files of the database, each held
// to the digest below:
//
//	DerivedGeneralCategory.txt  (extracted/)  Cc, Co, Cn
//	PropList.txt                              Bidi_Control, Noncharacter_Code_Point
//	DerivedCoreProperties.txt                 Default_Ignorable_Code_Point
//
// from https://www.unicode.org/Public/15.0.0/ucd/, put in one directory:
//
//	go run gen_policy.go -ucd DIR -package mcp -o policy_table.go
package main

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// sources are the files read, each with its digest and the values of its
// second field that the policy refuses.
var sources = []struct {
	name, digest string
	values       []string
}{
	{"DerivedGeneralCategory.txt", "fe29a45c0882500e591140aaa5c4f5067e6a5d746806148af34400c48b9c06f9", []string{"Cc", "Co", "Cn"}},
	{"PropList.txt", "e05c0a2811d113dae4abd832884199a3ea8d187ee1b872d8240a788a96540bfd", []string{"Bidi_Control", "Noncharacter_Code_Point"}},
	{"DerivedCoreProperties.txt", "d367290bc0867e6b484c68370530bdd1a08b6b32404601b8c7accaf83e05628d", []string{"Default_Ignorable_Code_Point"}},
}

func main() {
	ucd := flag.String("ucd", "", "directory holding the three Unicode 15.0.0 files")
	pkg := flag.String("package", "", "package of the file written")
	out := flag.String("o", "", "file to write")
	flag.Parse()
	if *ucd == "" || *pkg == "" || *out == "" {
		log.Fatal("usage: go run gen_policy.go -ucd DIR -package NAME -o FILE")
	}
	refused := make([]bool, 0x110000)
	for _, src := range sources {
		data, err := os.ReadFile(filepath.Join(*ucd, src.name))
		if err != nil {
			log.Fatal(err)
		}
		sum := sha256.Sum256(data)
		if got := hex.EncodeToString(sum[:]); got != src.digest {
			log.Fatalf("%s digests to %s, not the Unicode 15.0.0 file's %s", src.name, got, src.digest)
		}
		want := map[string]bool{}
		for _, v := range src.values {
			want[v] = true
		}
		found := map[string]bool{}
		lines := bufio.NewScanner(bytes.NewReader(data))
		for lines.Scan() {
			line, _, _ := strings.Cut(lines.Text(), "#")
			fields := strings.Split(line, ";")
			if len(fields) < 2 {
				continue
			}
			value := strings.TrimSpace(fields[1])
			if !want[value] {
				continue
			}
			found[value] = true
			lo, hi := parseRange(strings.TrimSpace(fields[0]))
			for r := lo; r <= hi; r++ {
				refused[r] = true
			}
		}
		for _, v := range src.values {
			if !found[v] {
				log.Fatalf("%s has no line for %s", src.name, v)
			}
		}
	}
	// Tab and line feed are the two controls a text may hold.
	refused['\t'], refused['\n'] = false, false
	var ranges [][2]rune
	for r := rune(0); r < 0x110000; r++ {
		if !refused[r] {
			continue
		}
		if n := len(ranges); n > 0 && ranges[n-1][1] == r-1 {
			ranges[n-1][1] = r
		} else {
			ranges = append(ranges, [2]rune{r, r})
		}
	}
	sort.Slice(ranges, func(i, j int) bool { return ranges[i][0] < ranges[j][0] })
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gen_policy.go from the Unicode 15.0.0 character database; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", *pkg)
	fmt.Fprintf(&b, "// displayRefused is every code point display policy 1 refuses -- Cc but tab\n")
	fmt.Fprintf(&b, "// and line feed, Bidi_Control, Default_Ignorable_Code_Point, Co, Cn and\n")
	fmt.Fprintf(&b, "// Noncharacter_Code_Point, as Unicode 15.0.0 assigns them -- as sorted,\n")
	fmt.Fprintf(&b, "// disjoint inclusive ranges, no two adjacent. %d ranges.\n", len(ranges))
	fmt.Fprintf(&b, "var displayRefused = [...]codeRange{\n")
	for _, r := range ranges {
		fmt.Fprintf(&b, "\t{0x%04X, 0x%04X},\n", r[0], r[1])
	}
	fmt.Fprintf(&b, "}\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}
}

// parseRange reads "XXXX" or "XXXX..YYYY".
func parseRange(s string) (rune, rune) {
	first, last, ok := strings.Cut(s, "..")
	if !ok {
		last = first
	}
	lo, err := strconv.ParseUint(first, 16, 32)
	if err != nil {
		log.Fatalf("code point %q: %v", first, err)
	}
	hi, err := strconv.ParseUint(last, 16, 32)
	if err != nil || hi < lo || hi > 0x10FFFF {
		log.Fatalf("code point range %q", s)
	}
	return rune(lo), rune(hi)
}
